### ISSUE TITLE
scheduler_node : left vs lost resources

### ISSUE THREAD

**Issue by stonier** [utexas-bwi/concert_scheduling#23]
This is a carry over from https://github.com/utexas-bwi/rocon_scheduler_requests/issues/10. I'll try to crystallise what was there and then raise the issue.

**Summary**
- We have resources within a request going missing
- The scheduler should not act on this, just pass notification back to the requester
- The requester has the freedom to choose its own response
  - cancel and resubmit, or delay, or other...

**Current Status**

Resources are currently tracked with a [status flag](https://github.com/robotics-in-concert/rocon_msgs/blob/hydro-devel/scheduler_msgs/msg/CurrentStatus.msg#L25) with `AVAILABLE`, `ALLOCATED` and `MISSING` values. If a resource disappears from the conductor's `/concert/conductor/concert_clients` publication, then it is flagged as `MISSING` and published in turn on `/concert/scheduler/resource_pool`.

**Issues**
1. _There are actually two kinds of missing_ - `left` and `lost`

The first is when the concert client has _left_ the concert. If this happens and it does come back, it will come back under a different rocon uri (probably with a postfixed counter to the name, e.g. kobuki2 instead of kobuki). The second when it just loses its network connection to the concert and will come back at some point. 

The conductors' `concert_clients` topic provides the necessary information for both cases. 

When a client has `left`, it just disappears from the topic's list of clients and this is the case that is handled in the [resource pool update](https://github.com/utexas-bwi/concert_scheduling/blob/master/concert_resource_pool/src/concert_resource_pool/resource_pool.py#L539). 

When a client is `lost`, it will (have a bit of work to do this week on this) get shown in the `client_status` variable which indicates its current connectivity, e.g.

```
clients: 
  - 
    name: kobuki
    gateway_name: kobukib093a49d98e747cd9ef2f1cb337408f3
    platform_info: 
      uri: rocon:/pc/kobuki/hydro/precise
      version: acdc
      icon: 
        resource_name: ''
        format: png
    client_status: connected
    app_status: running
```

**Questions**
- Should `left` clients stay in the resource pool? This is important for tracking an individually left resource in a request containing multiple resources.
- Should have status flags that reflect both these conditions in https://github.com/robotics-in-concert/rocon_msgas/blob/hydro-devel/scheduler_msgs/msg/CurrentStatus.msg#L25?
